title: Page Transition 2
description: > # this means to ignore newlines until "baseurl:"
  Another take on page transitions. This time, with client-side routing and an object approach via Backbone.js.
baseurl: "/page-transition-2" # the subpath of your site, e.g. /blog/
url: "http://swashcap.github.io" # the base hostname & protocol for your site

permalink: "/post/:year/:month/:title/"

exclude: ["node_modules", "gulpfile.js", "package.json"]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
